<?php
/**
 * Magento Bridge
 *
 * @author Yireo
 * @package Magento Bridge
 * @copyright Copyright 2013
 * @license Open Source License
 * @link http://www.yireo.com
 */
?>

<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="magebridge_edit_form">
<div class="columns ">

<div class="side-col" id="page:left">
<?php echo $this->getMenu(); ?>
</div>

<div class="main-col" id="content">
<div class="main-col-inner">

<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:50%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader('Support &amp; updates'); ?></h3></td>
        <td class="formbuttons" align="right">
            <?php echo $this->getSaveButtonHtml(); ?>
            <button type="button" class="scalable" onclick="doSubmit();"><span><?php echo $this->__('Save'); ?></span></button>
        </td>
	</tr>
</table>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Support key'); ?></h4>
    </div>
    <div class="fieldset ">
        <table cellspacing="5" class="form-list">
        <tbody>
            <tr>
                <td width="300"><label for="license_key"><?php echo $this->__('Support key'); ?></label></td>
                <td><input type="text" class="input-text" size="40" name="license_key" id="license_key" value="<?php echo $this->getLicenseKey(); ?>" /></td>
            </tr>
        </tbody>
        </table>
    </div>
</div>

<?php echo $this->getBlockHtml('formkey'); ?>
</form>

<script type="text/javascript">
var magebridgeForm = new varienForm('magebridge_edit_form');
function doSubmit() {
    magebridgeForm.submit();
    return true;
}
</script>
