<html>
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('global_notices') ?>
<?php echo $this->getChildHtml('global_messages') ?>
<?php echo $this->getChildHtml('breadcrumbs') ?>
<?php echo $this->getChildHtml('content') ?>
<?php echo $this->getChildHtml('left') ?>
<?php echo $this->getChildHtml('right') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
